version: '2.1'

services:
  g-db-postgresql-master:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=g_user
      - POSTGRESQL_PASSWORD=g_password
      - POSTGRESQL_DATABASE=g_db
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
  g-db-postgresql-slave:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5433'
    depends_on:
      - g-db-postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=g-db-postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_USERNAME=g_user
      - POSTGRESQL_PASSWORD=g_password
      - POSTGRESQL_DATABASE=g_db

  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_USERNAME=g_user
      - RABBITMQ_PASSWORD=g_password
      - RABBITMQ_ERL_COOKIE=AJsbnj5kSh54

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on: 
      - zookeeper
  
